In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
DATA_PROCESSED = Path("data_processed")

df = pd.read_csv(DATA_PROCESSED/"battery_master_dataset.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (84515376, 8)

    time  voltage  current  temperature  cycle dataset chemistry      cell_id
0    0.0   4.2937      0.0          0.0      0    CALB   Unknown  CALB_0_B182
1   30.0   4.2937      0.0          0.0      0    CALB   Unknown  CALB_0_B182
2   60.0   4.2937      0.0          0.0      0    CALB   Unknown  CALB_0_B182
3   90.0   4.2934      0.0          0.0      0    CALB   Unknown  CALB_0_B182
4  120.0   4.2937      0.0          0.0      0    CALB   Unknown  CALB_0_B182

In [3]:
df = df.dropna()

df = df[df["voltage"] > 0]
df = df[df["current"].abs() < 100]

print("After cleaning:", df.shape)

After cleaning: (84289889, 8)

In [4]:
print(df["dataset"].value_counts())

dataset
Stanford    78550888
CALCE        4578904
CALB         1023220
NASA          136877
Name: count, dtype: int64

In [5]:
print(df["dataset"].value_counts())

dataset
Stanford    78550888
CALCE        4578904
CALB         1023220
NASA          136877
Name: count, dtype: int64

In [6]:
df.groupby("dataset")["cycle"].nunique()

dataset
CALB         208
CALCE       1579
NASA           1
Stanford    1420
Name: cycle, dtype: int64

In [7]:
df_aug = df.copy()

df_aug["voltage"] = df_aug["voltage"] + \
    np.random.normal(0, 0.003, len(df_aug))

In [8]:
features = df.groupby(["cell_id","cycle","dataset"]).agg({
    "voltage":["mean","min","max","std"],
    "current":["mean"],
    "temperature":["mean"],
})

features.columns = ["_".join(col) for col in features.columns]
features = features.reset_index()

features.head()

,cell_id,cycle,dataset,voltage_mean,voltage_min,voltage_max,voltage_std,current_mean,temperature_mean
0,B0005,0,NASA,4.145472,3.232553,4.209761,0.107154,25.077792,0.626191
1,B0006,0,NASA,4.152354,3.305700,4.201837,0.087784,25.152395,0.625240
2,B0007,0,NASA,4.142648,3.231007,4.214712,0.118016,24.746185,0.642030
3,B0018,0,NASA,4.135312,2.968585,4.201895,0.113623,25.545536,0.668788
4,B0025,0,NASA,4.144060,2.802418,4.209631,0.118431,27.601881,0.678365

In [9]:
features.to_csv(DATA_PROCESSED/"battery_features_week2.csv", index=False)

print("Saved battery_features_week2.csv")

Saved battery_features_week2.csv